---
- name: install-Check-MK-CentOS7
  hosts: "node"
  tasks:
    - name: Disable SELinux
      selinux:
        state: disabled
    - name: update
      shell: "yum update -y"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

## Package requiment
    - name: Package requiment
      yum:
        name: "{{ package }}"
      vars:
        package:
        - epel-release
        - wget 
        - xinetd
        - openssl
        - python-pip
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    - name: enable xinetd
      service: 
        name: xinetd
        enabled: yes  
    - name: start xinetd
      service:
        name: xinetd
        state: restarted
#Install passlib
    - name: update
      shell: "pip install passlib"
      
#Get && installation Check_MK
    - name: Download rpm check_mk 1.5
      get_url:
        url: https://mathias-kettner.de/support/1.5.0p2/check-mk-raw-1.5.0p2-el7-38.x86_64.rpm
        dest: /root      
    - name: Install rpm check_mk 1.5
      shell: "yum install -y check-mk-raw-1.5.0p2-el7-38.x86_64.rpm"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
      
#Create OMD
    - name: Create OMD
      shell: "omd create {{ omd_name }}"
#Start OMD   
    - name: Start OMD
      shell: "omd start {{ omd_name }}"
      
#Open port firewalld
    - name: open port 80
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
    - name: open port 6556
      firewalld:
        port: 6556/tcp
        permanent: yes
        state: enabled
    - name: restart firewalld
      service: 
        name: firewalld
        state: restarted      

## Change pass_cmkadmin
    - htpasswd:
        path: /omd/sites/{{ omd_name }}/etc/htpasswd
        name: cmkadmin
        password: "{{ pass_cmkadmin }}"
 
########################################################################################################
#ansible-playbook install-checkmk-c7.yml --extra-vars '{"omd_name":"admin","pass_cmkadmin":"123456aA"}'#
########################################################################################################  

